---
- hosts: webservers
  remote_user: root

  tasks:
    - name: install the latest version of httpd
      yum: name=httpd state=latest 
    
    - name: ensure that httpd is running and enabled
      service: name=httpd state=started enabled=yes

    - name: copy index.html template
      template: src=templates/index.html.j2 dest=/var/www/html/index.html

    - name: open port 80/tcp in firewalld
      firewalld: port=80/tcp permanent=true state=enabled immediate=yes
