---
# tasks file for openscap

- set_fact:
    openscap_policies: "{{ openscap_policies_rhel6 }}"
  when: ansible_distribution_major_version|int == 6

- set_fact:
    openscap_policies: "{{ openscap_policies_rhel7 }}"
  when: ansible_distribution_major_version|int == 7

- name: Installing the OpenSCAP client
  yum:
    name: "rubygem-foreman_scap_client"
    enablerepo: "rhel-{{ ansible_distribution_major_version }}-server-satellite-tools-{{ satellite_version }}-rpms"
    state: latest

- name: Update /etc/foreman_scap_client/config.yaml
  template:
    src: "templates/config.yaml.j2"
    dest: /etc/foreman_scap_client/config.yaml

- name: Running the OpenSCAP client policies
  shell: "/usr/bin/foreman_scap_client {{ item.policy_id }}"
  with_items: "{{ openscap_policies }}"
